version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_Alpine
    container_name: django-project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/django/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    container_name: postgres_container
    tty: true 
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
        - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
    restart: always

  pgadmin:
    image: dpage/pgadmin4:5.2
    container_name: pgadmin_container
    tty: true
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-9000}:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: always

volumes:
  pg_data:
    # external: true
  pgadmin:
